# Generated by Django 4.2.2 on 2023-07-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_es_admin_usuario_es_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perfil'),
        ),
    ]
