# Generated by Django 4.2.2 on 2023-07-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_categoria_alter_publicaciones_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
