# Generated by Django 4.2.2 on 2023-07-11 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicaciones', '0003_publicaciones_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posteos_usario', to=settings.AUTH_USER_MODEL),
        ),
    ]
