# Generated by Django 4.2.2 on 2023-06-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicaciones',
        ),
    ]
